### ISSUE TITLE
Platform yr not used anymore on version 2021.8.8

### ISSUE THREAD

**Issue by Tweakerd** [ticapix/home-assistant_sdm630#1]
Hi Ticapix, 

Thanks for this information, but for me it's not working.. 
The problem is that in the today version of Homa assistant (Core Version 2021.8.8) there is no support anymore for the 
platform: yr.
Therefore it is not working anymore. 
Do you know how to resolve this?

It woud be appreciated :D

regards,

René

**Comment by ticapix** [comment]
Hi @Tweakerd 

Thank you for your message.

`yr` is not required for modbus and can be removed. I updated the readme in https://github.com/ticapix/home-assistant_sdm630/commit/4d6486e2c70ab80e9f18179dec4b7e6b69aa6256

Please reopen is this doesn't fix the issue.

Best
